### ISSUE TITLE
[phub] Announcements created with no delivery targets remain in 'awaiting_delivery' state

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/platform-hub#101]
**Steps to recreate:**

1. When logged into the platform hub with an admin account, select 'Announcements' -> 'New'
2. Fill in all fields, but leave the bottom section entirely blank (labelled `and announcements can be delivered outside of the hub`), so that it doesn't send email / slack notifications.
3. Hit 'Create' to fire off the announcement
4. View the announcement in the 'Announcements' tab

**Expected Behaviour:**
The 'Status' field should say something along the lines of 'delivered' / 'not_applicable' / 'viewable'. Maybe even drop off the 'Deliver to' field or put a similar message.

**Actual Behaviour:**
```
Deliver to:
Status: awaiting_delivery
```

Not sure if this is potentially adding additional load with any background jobs picking up things in `awaiting_delivery` state and trying to process them?

**Comment by jits** [comment]
Thanks @KashifSaadat – changing the `status` to something more appropriate makes sense.

You're right in that these announcements are continually being loaded at the moment – the load _should_ be negligible for a few announcements, but will get worse over time. So this is a good one to fix.

We should also not show the `Deliver to:` in the listing view, as you suggest.

**Comment by jits** [comment]
Turns out we already mark this case as `delivered`, but only when they have been published, and then picked up by the announcements processor. So we wouldn't get the query load discussed above.

However, it is still better to use a more appropriate status. So I'll change this to `no_delivery_required`.
