### ISSUE TITLE
Feature Flag toggle intermittently fails to show that changes were applied

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/platform-hub#105]
**Steps to recreate:**
1. Login to the Platform Hub with an account that has administrator privileges
2. Navigate to `/feature-flags/edit`
3. Drag toggle on/off or press the active/disabled buttons for any of the features a few times

**Expected response:**
On every toggle, the corresponding feature flag should be enabled or disabled accordingly

**Actual response:**
Intermittently when toggling the feature flag, the change doesn't apply successfully and the feature visually stays at its existing state. However, I can see a POST request is made to `api/feature_flags/projects` with the correct values and a 200 response code. On a manual page refresh I can see that the settings were updated correctly, so this is just a display issue. The following JS log is also output:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```

This was tested on both Google Chrome and Safari. Would be a low priority issue considering it still works mostly, just a little rendering issue.

**Comment by jits** [comment]
Indeed, I saw this whilst developing it, very infrequently – it sounded like some race condition. I'll have a closer look.
