### ISSUE TITLE
Generate kubecfg for a user token

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/platform-hub#166]
As a user
I want to download a fully functional kubeconfig file for my given user token on a project
So that I don't need to manually retrieve the API url and CA content and build the config myself

Related issue: https://github.com/UKHomeOffice/application-container-platform-board/issues/680
Partial PR: https://github.com/UKHomeOffice/platform-hub/pull/164

**Comment by jits** [comment]
https://github.com/UKHomeOffice/platform-hub/pull/176
