### ISSUE TITLE
[bug] 404 redirect immediately when typing user email to add to a project

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/platform-hub#233]
**Steps to recreate:**
1. Login to the Platform Hub
1. Navigate to a project that you have administrative control over: `https://[HUB-URL]/projects/detail/[PROJECT-NAME]`
1. Start typing a user's email address

**Expected Behaviour:**
- When typing the user's email address, the drop-down will show the related user with matching address

**Actual Behaviour:**
- When typing `.` as part of the email / username, the form automatically submits and immediately redirects you to the homepage. Responses below:

```
Request URI: /api/users/search/bob@?include_deactivated=false
Response Code: 200 OK
Response Message: []

Request URI: /api/users/search/bob.bobberson?include_deactivated=false
Response Code: 404 Not Found
```

**Comment by KashifSaadat** [comment]
I believe this is related: https://github.com/Casecommons/pg_search/issues/14

**Comment by jits** [comment]
@KashifSaadat – nice catch!

This _may_ not be related to that `pg_search` issue you referenced. There are possibly two separate issues here:

1. Typing certain characters immediately submits the autocomplete component.
1. The `404` being returned by the API is probably because no route is being matched (the `.xxxx` bit would be treated like a file extension, so we need to escape special characters).

**Comment by KashifSaadat** [comment]
Aha okay.

Just been testing, it doesn't immediately submit the autocomplete based on certain characters so looks like that bit is working as expected (submits for autocomplete when there's a slight pause in typing).

Escaping special characters sounds sensible :) Would just need to validate they still correctly get parsed and searched when passed to the search lib.

**Comment by jits** [comment]
@KashifSaadat –

> Would just need to validate they still correctly get parsed and searched when passed to the search lib.

We should just need to url escape the search string in the frontend. Then the backend should handle things as expected (i.e. it will unescape it).

**Comment by KashifSaadat** [comment]
Cool sounds good!
